### ISSUE TITLE
JSPM CLI v3 inconsistent

### ISSUE THREAD

**Issue by DanielKehoe** [InstallGuides/install-guide#2]
I've been experimenting with JSPM CLI v3 and the results are inconsistent.

I tried a small test case:

```
$ jspm build ./assets/scripts/yax-hack.js -i -p -o test-hack.html
ok   Built into dist/
ok   Linked ./dist/yax-hack-05aa5a05.js into test-hack.html (30.5KiB).
```
I was able to build, deploy and run this successfully.

I created a more complex test case that imports all the modules I intend to use for my project:
`assets/scripts/tags.js`
and tested it in the file `1.html`.

I tried
```
$ jspm build ./assets/scripts/tags.js -i -p -o 1.html
```
and results were inconsistent with each build attempt.

I got various errors on different tries:

```
$ jspm build ./assets/scripts/tags.js -i -p -o 1.html

Error: Could not load https://jspm.dev/prismjs (imported by assets/scripts/yax-markdown.js): Invalid status code 304 loading https://jspm.dev/prismjs. Not Modified

$ jspm build ./assets/scripts/tags.js -i -p -o 1.html

Error: Could not load https://jspm.dev/lit-element (imported by assets/scripts/yax-articles-list.js): Invalid status code 304 loading https://jspm.dev/lit-element. Not Modified

$ jspm build ./assets/scripts/tags.js -i -p -o 1.html

Error: Could not load https://jspm.dev/npm:lit-html@1/lib/shady-render.js (imported by https://jspm.dev/lit-element): Invalid status code 304 loading https://jspm.dev/npm:lit-html@1/lib/shady-render.js. Not Modified

$ jspm build ./assets/scripts/tags.js -i -p -o 1.html

Error: Could not load https://jspm.dev/commonmark (imported by assets/scripts/yax-markdown.js): Invalid status code 304 loading https://jspm.dev/commonmark. Not Modified

$ jspm build ./assets/scripts/tags.js -i -p -o 1.html

Error: Could not load https://jspm.dev/npm:lit-html@1/lit-html.js (imported by https://jspm.dev/lit-element): Invalid status code 304 loading https://jspm.dev/npm:lit-html@1/lit-html.js. Not Modified
```

I tried importing prismjs and commonmark from skypack:

```
import prismjs from 'https://cdn.skypack.dev/prismjs';
import commonmark from 'https://cdn.skypack.dev/commonmark';
```
I still got some errors:

```
$ jspm build ./assets/scripts/tags.js -i -p -o 1.html

Error: Could not load https://jspm.dev/lit-html/directives/until.js (imported by assets/scripts/yax-articles-list.js): Invalid status code 304 loading https://jspm.dev/lit-html/directives/until.js. Not Modified

$ jspm build ./assets/scripts/tags.js -i -p -o 1.html

Error: Could not load https://jspm.dev/npm:lit-html@1/lib/shady-render.js (imported by https://jspm.dev/lit-element): Invalid status code 304 loading https://jspm.dev/npm:lit-html@1/lib/shady-render.js. Not Modified
```

But after trying again, the build succeeded:

```
$ jspm build ./assets/scripts/tags.js -i -p -o 1.html
ok   Built into dist/
ok   Linked ./dist/tags-deb2f59e.js into 1.html (117.4KiB).
```
I tried running in my local browser and got a console error:

```
Uncaught TypeError: Cannot read property 'Parser' of null
    at new YaxMarkdown (tags-deb2f59e.js:367)
    at Object.execute (tags-deb2f59e.js:369)
    at i (s.min.js:1)
    at e (s.min.js:1)
    at s.min.js:1
```
So I can see compound problems here:

1. The JSPM CLI v3 build is inconsistent because of 304 Not Modified errors
2. After a successful build, there's an execution error that I don't understand and can't diagnose (presumably a problem with prismjs or commonmark).

@guybedford do you have any suggestions?

**Comment by DanielKehoe** [comment]
Preserved the test state in the branch test-jspm-cli.

**Comment by DanielKehoe** [comment]
Resolved the error:
```
Uncaught TypeError: Cannot read property 'Parser' of null
    at new YaxMarkdown (tags-deb2f59e.js:367)
    at Object.execute (tags-deb2f59e.js:369)
    at i (s.min.js:1)
    at e (s.min.js:1)
    at s.min.js:1
```
by using corrected ES6 import syntax:
```
import * as prismjs from 'https://cdn.skypack.dev/prismjs';
import * as commonmark from 'https://cdn.skypack.dev/commonmark';
```

JSPM CLI still has 304 Not Modified errors.

**Comment by DanielKehoe** [comment]
Also able to load prismjs and commonmark from the jspm.dev server:
```
import * as prismjs from 'https://jspm.dev/prismjs';
import * as commonmark from 'https://jspm.dev/commonmark';
``` 
Still getting repeated 304 Not Modified errors using the JSPM CLI.

**Comment by guybedford** [comment]
Thanks for your patience on this - I was working a contract last week for Vercel then was flying back to South Africa and finally managed to emerge from the jetlag enough to look into it!

I've added a fix for the 304 bug in https://github.com/jspm/jspm/commit/bb2c142b7011d662b14490abfdcc4f00be78259a, if you pull from master and rerun `npm run build-node` to refresh the jspm build, you should no longer get this error now.

I added the fix as per your last comment using `import * as commonmark` etc and that seems to get the build to work for me then.

Just let me know if you hit any further issues here.

**Comment by DanielKehoe** [comment]
Closing this issue. JSPM CLI v3 runs successfully.
